### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Dinesh1p0** [HeaTTheatR/Articles#1]
Bro facebook_desktop.py showing import error
This import showing error  👇👇👇👇👇👇

from FacebookDesktop.components.cards.chat_card import ChatCard

from FacebookDesktop.components.cards.friend_card import FriendCard

from FacebookDesktop.components.cards.story_card import StoryCard

**Comment by HeaTTheatR** [comment]
@Dinesh1p0 Attach error stacktrace.

**Comment by LukasSliacky** [comment]
hi Yuri, 
probably similar problem is with your new MeditationApp.
(tested on ubuntu + venv)

```
12:40:01 > (venv) > Articles/MeditationApp > python main.py 
[INFO   ] [Logger      ] Record log in /home/username/.kivy/logs/kivy_21-11-08_79.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/username/temp/Articles/venv/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/home/username/temp/Articles/venv/bin/python"
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "/home/username/temp/Articles/venv/lib/python3.8/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 21.1.0-devel (git-0747332 2021-01-20 focal-oibaf-ppa)'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) UHD Graphics 620 (KBL GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     from MeditationApp.Screens.RootScreen.root_screen import RootScreen
 ModuleNotFoundError: No module named 'MeditationApp
```

**Comment by HeaTTheatR** [comment]
@LukasSliacky 

https://user-images.githubusercontent.com/16930280/140738668-cbf73143-b13b-4df3-bbe7-c6b30711f12c.mov

**Comment by LukasSliacky** [comment]
After quick investigation in my case, i identifed two "problems":
1. i had to change;
    `from MeditationApp.Screens.RootScreen.root_screen import RootScreen` 
     to 
    `from Screens.RootScreen.root_screen import RootScreen`
(maybe problem between mac / linux platforms or python versions... I don't know... )
2. i used version `0.104.1` and after update to `1.0.0.dev` everything works fine (my bad, you are informing about 'Added load_all_kv_files method to MDApp class in last Changelog')

Now is everything works great, and i think that this issue can be closed (i think the Dinesh1p0's problem had same cause).

Thank you for your support.
Lukas Sliacky
